version: '2'
services:
  api:
    build: ./back-end-api
    ports:
      - '9000:9000'
  ui:
    build: ./front-end-app
    stdin_open: true
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048
    ports:
      - '3000:3000'
    links:
      - api
